name: Playwright Tests
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 14 * * *'  # Fixed cron syntax

jobs:
  run-tests:
    name: Run Playwright Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4  # Updated to v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Create .env file from secrets
      run: |
        echo "EMAIL=${{ secrets.EMAIL }}" > .env
        echo "PASSWORD=${{ secrets.PASS }}" >> .env

    - name: Install Dependencies
      run: npm ci  # Use ci instead of install for more reliable builds

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Install Allure Command-Line Tool
      run: npm install -g allure-commandline

    - name: Manage Historical Reports
      run: |
        if [ -d "allure-results" ]; then
          find "allure-results" -type f -name "*.json" -delete
        fi

        REPORTS_DIR="allure-results/history"
        mkdir -p "$REPORTS_DIR"

        if [ -d ".github/history" ]; then
          cp -R ".github/history"/* "$REPORTS_DIR/"
        fi

    - name: Run Playwright Tests
      run: npm run test || true
      env:
        EMAIL: ${{ secrets.EMAIL }}
        PASSWORD: ${{ secrets.PASS }}

    - name: Generate Allure Report
      if: always()
      run: allure generate allure-results --clean -o allure-report

    - name: Save historical data
      if: always()
      run: |  
        if [ -d "allure-report/history" ]; then
          mkdir -p .github/history
          cp -R "allure-report/history"/* ".github/history/"
        fi

    - name: Commit and Push Allure Results and Reports
      if: always()
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add .github/history
        git commit -m "Update historical Data Allure" || echo "No changes to commit"
        git push origin main

    - name: Deploy to GitHub Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./allure-report

    - name: Upload Artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

    # Count the number of tests
    - name: Run JavaScript script to count tests
      id: count_tests
      run: |
        output=$(node count_tests.js allure-report/data/behaviors.json)
        echo "::set-output name=passed::$(echo "$output" | awk '/Total Passed Tests:/ {print $4}')"
        echo "::set-output name=failed::$(echo "$output" | awk '/Total Failed Tests:/ {print $4}')"

    # Slack Notification
    - name: notify slack \#automation-test-reports
      id: slack
      uses: slackapi/slack-github-action@v1.24.0
            # https://api.slack.com/apps/<your-app-id>/incoming-webhooks
      with:
        channel-id: '#automation-test-reports' # slack channel #alerts-test
        payload: |
              {
                "text": "Expert automation test results",
                "blocks": [
                  {
                    "type": "section",
                    "text": {
                      "type": "mrkdwn",
                      "text": "Expert Test Automation Completed. \nPassed tests: ${{ steps.count_tests.outputs.passed }}\nFailed tests: ${{ steps.count_tests.outputs.failed }}\n To see the reports go to https://correlation-one.github.io/expert-e2e/"
                    }
                  }
                ]
              }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_NOTIFICATIONS_WEBHOOK }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK